# WEEK - 1 ASSIGNMENTS
## Data Science & Data Analytics Laboratory
### Name: Kinjal Raykarmakar
#### Section: CSE 3H
#### Roll No.: 29
#### Enrollment No.: 12018009019439

# Introduction to NumPy and Pandas

In [7]:
import numpy as np

## `np.arange()`
The native python `range()` function returns a generator object whereas, NumPy's `arange()` function returns a `np.ndarray` (N-dimensional Array) 

NumPy array as used, as they are known to be more efficient while working with complex ML models over native python code

`np.arange(start, end, step)` -> end exclusive

In [8]:
array = np.arange(20)
print(type(array))
print(array)

<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [14]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(10, 35, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34])

## `.shape()`
To get the dimension of the array. Shape of an NumPy array returns a `tupple` (immutable)

- Why `(20,)` - in single dimensional array? -> "," is actally a way to indicate a tupple. If we use `(20)` then, it will be interpreted as an integer
- Why not `(20, 1)`? -> Becasue that will infer a 2D array, not 1D anymore

In [9]:
print(array.shape)
print(type(array.shape))

(20,)
<class 'tuple'>


## Indexing
Indexing in a NumPy ndarray is very similar to a normal array

In [10]:
array[3]

3

In [11]:
# NumPy arrays are mutable
array[3] = 1000
print(array)

[   0    1    2 1000    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19]


## Reshaping
One condition for reshaping: The total no. of elements before and after reshaping should be same

In [17]:
array = np.arange(9) # this should have a shape: (9,) - having 9 elements
array.reshape(3, 3) # new shape is (3, 3) - having 9 elements

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# `np.zeros()`, `np.ones()` and `np.full()`
Create an array of all zeros/ones/(a value passed). The type of the internal elements are default `float`

The dimension of the array should be passed in the form of `tupple`

In [18]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.full((2, 2), 3)

array([[3, 3],
       [3, 3]])

# Identity Matrix

In [21]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Typecasting to NumPy Array

In [22]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
my_array = np.array(my_list)

print(my_array)
print(type(my_array))

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


NumPy functions don't genarally work in-place. We'll have to save the valur to the same variable to replace it

In [26]:
my_array = my_array.reshape((2, 4))
my_array = my_array.T
print(my_array)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


## NumPy methods
Concept of axis:
`axis = 0` is the first dimension (i.e. across rows), ... and so on. `axis` can be passed in almost all of the statistical methods

In [31]:
max = my_array.max()
min = my_array.min()
mean = my_array.mean()
mean = my_array.mean()
std = my_array.std(axis = 1)

print("Maximum:", max)
print("Minimum:", min)
print("Mean:", mean)
print("Standard Deviation:", std)

Maximum: 8
Minimum: 1
Mean: 4.5
Standard Deviation: [2. 2. 2. 2.]


In [34]:
num = []
for i in range(0, 5):
    num.append(np.random.randint(0, 2)) # generating random nos. within range (exclusive)
num = np.array(num)

print(num)
print(np.unique(num)) # finding the unique elements in an array

[1 1 1 0 0]
[0 1]


In [36]:
x = np.arange(1, 4)
y = np.arange(1, 7, 2)

print(x, y)
np.add(x, y)

[1 2 3] [1 3 5]


array([2, 5, 8])

In [40]:
num = np.arange(1, 10, dtype=float).reshape(3, 3)

print(num)

print(np.max(num))
print(np.max(num, axis=0))
print(np.max(num, axis=1))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
9.0
[7. 8. 9.]
[3. 6. 9.]


In [43]:
num[1, 2] = np.NaN # setting Not a Number

print(num)
np.max(num, axis=0)

[[ 1.  2.  3.]
 [ 4.  5. nan]
 [ 7.  8.  9.]]


array([ 7.,  8., nan])

# Pandas

In [2]:
import pandas as pd

In [3]:
data = pd.read_excel(r"./test_data.xlsx")

## `.head()`
Printing first 5 rows. If `n` is passed in the function, then first *n* rows will be printed

In [6]:
data.head() # prints top 5 rows

f1  f2   f3   f4
0   1   2  3.0  4.0
1   5   6  NaN  7.0
2   0   6  9.0  NaN

## More Pandas methods

In [7]:
data.isnull() # returns a boolean matrix

f1     f2     f3     f4
0  False  False  False  False
1  False  False   True  False
2  False  False  False   True

In [9]:
data.isnull().sum() # counts the number of null found in each coloumn

f1    0
f2    0
f3    1
f4    1
dtype: int64

In [11]:
data.dropna() # drops rows with null values

f1  f2   f3   f4
0   1   2  3.0  4.0

In [13]:
data.dropna(axis = 1) # using axis=1 specifies coloumn

f1  f2
0   1   2
1   5   6
2   0   6